### ISSUE TITLE
.exe file

### ISSUE THREAD

**Issue by ShadowDragun** [Argent77/A7-DlcMerger#3]
This is probably just because I'm so new here but I once I download and unzip this I cannot find the .exe file anywhere.

**Comment by Argent77** [comment]
Make sure you download the archive from the [Releases section](https://github.com/Argent77/A7-DlcMerger/releases). Choose the file that matches your system, e.g. for Windows use one of the `win-32bit-xxx` or `win-64bit-xxx` packages. Do not choose any of the "Source code" links though. They are automatically generated by GitHub and don't contain any executable files.

The downloaded zip file should contain the file `setup-DlcMerger.exe` and a folder `DlcMerger`. If the executable file is missing it could be because of your antivirus tool. There are occasionally reports that they sometimes erroneously mark these files as a potential threat because of the compression method used to shrink these files to an acceptable size.

**Comment by ShadowDragun** [comment]
It was my antivirus tool, thank you so much!
