### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by WildKing-droid** [Argent77/A7-DlcMerger#6]
Uhh, hello can you help with the linux installation of DLC Merger. for windows there's exe and for linux version there's nothing.

**Comment by Argent77** [comment]
On Linux it is common to place the WeiDU installer binaries into the path and use `weinstall` from the command line to install mods. That's why there is no Linux version included in the mod package.

However, you can manually prepare a setup binary for easier installation by downloading the Linux version of WeiDU from here: https://github.com/WeiDUorg/weidu/releases/latest

Unpack the file `weidu` from the WeiDU archive into the game directory and rename it to `setup-DlcMerger`. Make sure it is executable. Also unpack the DLC Merger archive into the game directory. Then you can run the binary to install the mod.

The same procedure can be used for other mods that don't provide a binary for installation. Just rename the WeiDU binary to the name of the mod folder with the `setup-` prefix.

**Comment by WildKing-droid** [comment]
Ohhh i understand now, but the problem now is, linux native version of steam's Baldur's Gate EE don't have the dialog.tlk file in the game folder, it is in the lang folder and it gave me an error, i manually copied the dialog file and now the installer gives me an error that setup-dlcmerger.tp2 not found. If I just install the windows version with proton would it be easier to install all this? I was playing the windows version with proton and installed DLCMerger with Unfinished Buisness and Classic Movies and didn't saw any differences as if the mods didn't work at all, also custom portraits didn't work in windows proton version for some reason, but in linux native portraits are working.
![Screenshot from 2023-08-18 11-29-34](https://github.com/Argent77/A7-DlcMerger/assets/84460621/3ce02c22-7bc9-4487-bbcd-e76b20e54440)

**Comment by Argent77** [comment]
The `dialog.tlk` found in dedicated language folders is true for all Enhanced Edition games on all platforms. The WeiDU installer can handle this setup quite well for some time. There is no need to copy the file to the main directory of the game.

The problem shown on your screenshot is more likely because the game is installed on a case-sensitive filesystem. This is (still) a big issue on Linux and will cause all kinds of trouble, including the error in your screenshot where the installer cannot find the mod script because it uses different casing.

I would recommend to create a copy of the game in another folder that has been made case-insensitive. [This topic](https://www.gibberlings3.net/forums/topic/28516-the-linux-users-guide-to-installing-mods-on-the-enhanced-editions/) on the G3 Forums describes several methods how to accomplish that.

Having a modded game in a folder outside of Steam control also has the advantage that the mod installation is not destroyed or corrupted if Steam performs update or repair operations on the game. The downside is, however, that you can't launch the game through the Steam client and Steam-specific features, like cloud saves or achievements, are unavailable.

**Comment by WildKing-droid** [comment]
Too much hassle for me honestly, I will try with the proton version again, but thanks for clearing stuff out for me.
